### PR TITLE
Changed how Item data is retrieved from the json object;

### PR DESCRIPTION
**Pull request by zethon**

### CODE REVIEW

**Comment by charmyt** [comment]
You can probably also delete that big comment about using [0] to access top level elements.

**Comment by charmyt** [comment]
Oh you already did that. Ignore my previous comment.

**Comment by charmyt** [comment]
This crashes in my env.

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.305] cannot use operator[] with a string argument with array

```

**Comment by charmyt** [comment]
And so that's why I had that long comment there.

**Comment by charmyt** [comment]
In ItemFactory
`nl::json json;`
Is passed to the Item constructor by reference? But this is on the stack right? So that shouldn't even work. Does it create a copy? In the process of copying itself does it alter the top level of the json structure? 

Is there a better way to create the json object and pass it to the Item constructor?

**Comment by zethon** [comment]
Per my note on AMB, I think there's a problem with copying the JSON object. I'm not sure if it's a bug somewhere or if copying just isn't supported (in which case I'd expect the object to be marked as non-copyable).

**Pull request closed without merging**
